version: '3'
services:
  web:
    container_name: php-book-app-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
    command: bash -c "sh docker-init-setup.sh && apache2-foreground"
    ports:
      - "5000:80"
